spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/techshopping
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.example.Tech: DEBUG
